@Lamp_HostAddress = http://localhost:8080

### Check lamp status
GET {{Lamp_HostAddress}}/check-status
Accept: application/json

###

### Turn on the lamp
POST {{Lamp_HostAddress}}/execute/turn-on
Accept: application/json

###

### Turn off the lamp
POST {{Lamp_HostAddress}}/execute/turn-off
Accept: application/json

###

### Set brightness to 75
POST {{Lamp_HostAddress}}/execute/set-brightness
Content-Type: application/json

{
  "input": 75
}

###

### Set color to purple
POST {{Lamp_HostAddress}}/execute/set-color
Content-Type: application/json

{
  "input": "#FF00FF"
}

###

### Register the lamp
POST {{Lamp_HostAddress}}/register
Accept: application/json
